### ISSUE TITLE
Fix horribly broken peg-outs

### ISSUE THREAD

**Issue by elsirion** [fedimint/minimint#1]
We don't consider change right now and bleed money in fees. To fix this we need:

- [x] deterministic change address generation (include randomness beacon in wallet consensus)
- [x] fee-aware coin selection
- [x] fix panic on peg-out due to the faulty assumption that everyone commits their signatures in the same (directly following) round
- [x] recognize change after it has been confirmed/stop broadcasting tx
- [ ] CPFP on congestion

**Comment by jkitman** [comment]
Replaced by #233.
