### ISSUE TITLE
Make mint client coin selection more intelligent

### ISSUE THREAD

**Issue by elsirion** [fedimint/minimint#11]
After the transaction refactor there is now the possibility to have change outputs that issue mint tokens back to the sender. This means that the client does not need to fail if an amount can not be represented with tokens in possession. Instead larger ones can be used and change returned to self.

**Comment by DON-MAC-256** [comment]
Significant [theoretical work](https://scalingbitcoin.org/papers/simulation-based-evaluation-of-coin-selection-strategies.pdf) has been done on coin selection for Bitcoin. That work should help with this task, especially if selection algorithms may be reused.

**Comment by elsirion** [comment]
I think this will be very valuable for the wallet part (that also needs better coin selection). This issue is about the blind tokens which are quite a bit different from BTC (amount tiers, less privacy concerns, spends are cheap) but will be interesting to see what can be transferred.

The more pressing, short term issue though is to make coin selection not fail just because we don't have the right denominations. That's an artifact from before there was change. I need to remodel the client after the LN module gets in anyway, so might do it then.

**Comment by DON-MAC-256** [comment]
Does the solution to this involve an extra step of having the mint "break" a few larger tokens into smaller change before sending the exact amount to the receiving party? Or is there some mechanism for sending change tokens back from the receiver?

A nice set of message flowcharts would help to clarify the stages of this process.

**Comment by elsirion** [comment]
> Does the solution to this involve an extra step of having the mint "break" a few larger tokens into smaller change before sending the exact amount to the receiving party? Or is there some mechanism for sending change tokens back from the receiver?

That's how it would work right now. An alternative with the current non-LN codebase would be the receiver giving blind tokens to the sender and the sender creating the transaction, allowing for change. Since the blind tokens are kind of encrypted anyway that should work too.

Once LN is integrated ideally every transaction is sent to an invoice, if the invoice happens to be inside the federation it can be accounted internally, otherwise it's handed off to the LN gateway. E.g. to send the user would create a transaction that has tokens as inputs and both a lightning contract as well as some change blind tokens as outputs.

Due to this upcoming change I've been a bit hesitant to overly improve or document this so far.

**Comment by DON-MAC-256** [comment]
> Once LN is integrated ideally every transaction is sent to an invoice, if the invoice happens to be inside the federation it can be accounted internally, otherwise it's handed off to the LN gateway. E.g. to send the user would create a transaction that has tokens as inputs and both a lightning contract as well as some change blind tokens as outputs.
> 
> Due to this upcoming change I've been a bit hesitant to overly improve or document this so far.

It looks like #23 deserves more intensive review, as a step in that direction!
