### ISSUE TITLE
Build audit functionality into modules

### ISSUE THREAD

**Issue by elsirion** [fedimint/minimint#128]
Each module knows its assets and liabilities, the `Module` trait should expose these and assert that after every round assets>liabilities.

**Comment by jkitman** [comment]
What if we made `TxInput` and `TxOutput` traits instead that require implementing `amount() -> Amount` that way we can perform the audit in the `MinimintConsensus` to keep that logic in one place?

Additionally I was thinking that we should make `ConsensusItem` a trait and begin to break the dependency of `MinimintConsensus` on specific modules.  Long-term the goal would be to have the `minimint` crate not depend on any specific module.  Instead there would only need to be a small amount of wiring code to add the modules to the server.  Developers could even implement modules in separate repos with no need to modify the consensus code, just import it as a dependency.
