### ISSUE TITLE
Integration Tests: lightning-cli enters infinite loop.

### ISSUE THREAD

**Issue by wiredhikari** [fedimint/minimint#138]
LN node can't open a new channel during integration tests .Link to [logs](https://github.com/fedimint/minimint/runs/6826014312?check_suite_focus=true#step:6:158420)

**Comment by wiredhikari** [comment]
Fixed by: [#136](https://github.com/fedimint/minimint/pull/136)

**Comment by elsirion** [comment]
Did you find out what exactly fixed it?

**Comment by wiredhikari** [comment]
> Did you find out what exactly fixed it?

In nixos-21.11, clightning 0.10.2 was being pulled while in nixos-22.05; clightning 0.11.1 is being pulled.
