### ISSUE TITLE
Remove `bitcoinconsensus` rust-bitcoin feature

### ISSUE THREAD

**Issue by justinmoon** [fedimint/minimint#143]
One problem I encountered making the mobile app was that the wallet module currently enables the `bitcoinconsensus` feature on `rust-bitcoin` which compiles bitcoin core at build time.

The compilation was broken in the mobile environment, and I didn't want to debug that because we only use `bitcoinconsensus` functionality in [this unittest](https://github.com/fedimint/minimint/blob/master/modules/minimint-wallet/src/lib.rs#L1335).

It would be nice to only compile bitcoin core in situations where we need it.

**Comment by Maan2003** [comment]
I made it optional in #140 
https://github.com/fedimint/minimint/pull/140/files#diff-e9a6c7a781d90136e43167effa40885130cf379069c8682cea4e7127a593b336R9

**Comment by elsirion** [comment]
I think this was fixed.
