### ISSUE TITLE
Self-hosted GitHub Actions runners

### ISSUE THREAD

**Issue by justinmoon** [fedimint/minimint#217]
Our CI is kinda slow. It's been getting better recently, but would still be nice if it was faster. One way is to just run CI on a faster server.

It seems that GitHub Actions doesn't offer better servers, but they do offer ["self-hosted runners"](https://docs.github.com/en/actions/hosting-your-own-runners). Someone should explore how feasible this is. Fedimint has received some donations which can pay for the servers.

I also saw a hosted service called [buildjet](https://buildjet.com/for-github-actions) which might be better than trying to actually manage the servers ourselves.

**Comment by elsirion** [comment]
I think hosted services are the only sane way imo if we want to stick to GH actions. There seems to be no OS orchestration infrastructure to spawn and destroy containers for each run. The GH actions runner provided by GH simply runs stuff on bare metal/wherever it's installed, that's a non-starter (see #219).

When I look at buildjet the pricing seems on the high side. You can get a potent server for under 100$/month and not worry about how many minutes you use. The same 100$ give you 6250min with their 8 vcore offering (idk if a vcore is like a thread on most CPUs or an actual core), which is ~4days of continuously running stuff. The good thing, as far as I can see, is that they can deal with peaks well, like give us n of these machines in parallel.

In the past I ran my own droneCI instance which was quite nice and offered all the features one would expect, but I'm not sure I want to get into that right now.
