### ISSUE TITLE
Consistent developer CLI units

### ISSUE THREAD

**Issue by justinmoon** [fedimint/minimint#237]
- `scripts/pegin.sh` takes an argument with `btc` unit
- `mint-client-cli pegout` takes an amount argument with `sat` unit
- `mint-client-cli ln-invoice` takes an argument with `millisat` unit

etc ... it's a little confusing to remember which command uses which unit.

I propose defaulting to sats in all cases, but allowing `1234btc` or `5678msat` suffixes to specify other units.

Thoughts?

**Comment by NicolaLS** [comment]
agreed

**Comment by NicolaLS** [comment]
closed by #259
