### ISSUE TITLE
Error messages when exiting nix-shell

### ISSUE THREAD

**Issue by justinmoon** [fedimint/minimint#243]
When I exit `nix-shell` after running out shell scripts I see the following output. We shouldn't print `panic` messages because the developer might think they did something wrong. Perhaps we could with kill processes in reverse order so that `server` instances are killed before `bitcoind` / `lightningd`? 

<details>
  <summary>logs ...</summary>
  
```
exit
2022-07-11T14:56:42Z tor: Thread interrupt
2022-07-11T14:56:42Z torcontrol thread exit
2022-07-11T14:56:42Z Shutdown: In progress...
2022-07-11T14:56:42Z opencon thread exit
2022-07-11T14:56:42Z addcon thread exit
2022-07-11T14:56:42Z msghand thread exit
Lost connection to the RPC socket.
Lost connection to the RPC socket.
Lost connection to the RPC socket.
2022-07-11T14:56:42Z net thread exit
Justins-MacBook-Pro% 2022-07-11T14:56:42Z DumpAnchors: Flush 0 outbound block-relay-only peer addresses to anchors.dat started
2022-07-11T14:56:42Z DumpAnchors: Flush 0 outbound block-relay-only peer addresses to anchors.dat completed (0.02s)
2022-07-11T14:56:42Z scheduler thread exit
2022-07-11T14:56:42Z Writing 0 unbroadcast transactions to disk.
2022-07-11T14:56:42Z Dumped mempool: 2.5e-05s to copy, 0.018449s to dump
mint 3: thread 'main' panicked at 'Bitcoind returned an error: JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })))', modules/minimint-wallet/src/bitcoincore_rpc.rs:36:14
mint 3: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
mint 3: thread 'tokio-runtime-worker' panicked at 'Peer connection was droppedthread 'tokio-runtime-worker' panicked at 'Peer connection was dropped', /Users/justin/ecash/minimint/minimint/src/net/peers.rs', /Users/justin/ecash/minimint/minimint/src/net/peers.rs:311:37
mint 3: :311:37
mint 1: thread 'main' panicked at 'Bitcoind returned an error: JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })))', modules/minimint-wallet/src/bitcoincore_rpc.rs:36:14
mint 1: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
mint 1: thread 'tokio-runtime-worker' panicked at 'Peer connection was dropped', /Users/justin/ecash/minimint/minimint/src/net/peers.rs:311:37
mint 1: thread 'tokio-runtime-worker' panicked at 'Peer connection was dropped', /Users/justin/ecash/minimint/minimint/src/net/peers.rs:311:37
mint 1: thread 'tokio-runtime-worker' panicked at 'Peer connection was dropped', /Users/justin/ecash/minimint/minimint/src/net/peers.rs:311:37
2022-07-11T14:56:42Z [default wallet] Releasing wallet
2022-07-11T14:56:42Z Shutdown: done
mint 0: thread 'main' panicked at 'Bitcoind returned an error: JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })))', modules/minimint-wallet/src/bitcoincore_rpc.rs:36:14
mint 0: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
mint 0: thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'Peer connection was droppedPeer connection was dropped', ', /Users/justin/ecash/minimint/minimint/src/net/peers.rs:311:37
mint 0: /Users/justin/ecash/minimint/minimint/src/net/peers.rs:311:37
mint 2: thread 'main' panicked at 'Bitcoind returned an error: JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })))', modules/minimint-wallet/src/bitcoincore_rpc.rs:36:14
mint 2: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
mint 2: thread 'tokio-runtime-worker' panicked at 'Peer connection was dropped', /Users/justin/ecash/minimint/minimint/src/net/peers.rs:311:37
mint 2: thread 'tokio-runtime-worker' panicked at 'Peer connection was dropped', /Users/justin/ecash/minimint/minimint/src/net/peers.rs:311:37
```

</details>

Also, it seems like the PIDs of the `server` processes are never written to our `.pid` file. Seems like [these two lines](https://github.com/fedimint/minimint/blob/master/scripts/start-fed.sh#L12) fail. I mention here because killing processes in reverse order won't work if the `panic`'ing process PIDs aren't in our PID file!

**Comment by dpc** [comment]
I'd say the code should not be panicking on connection errors or external service responding with an error.

**Comment by NicolaLS** [comment]
Opened a PR, but I noticed that 

1. If actually put in params in `source ./scripts/build.sh [fed_size] [dir]` you'd have to remove the `cd $CFG_DIR` in the `stard-fed.sh` I thought I could fix this easily but could not figure it out 
2. the `ln_gateway` does not get killed, The problem is that it is beeing run as a plugin : `lightningd --dev-fast-gossip --dev-bitcoind-poll=1 --network regtest --bitcoin-rpcuser=bitcoin --bitcoin-rpcpassword=bitcoin --lightning-dir=$LN1_DIR --addr=127.0.0.1:9000 --plugin=$BIN_DIR/ln_gateway --minimint-cfg=$CFG_DIR &` I think we have to use `killall ln_gateway` for that but I think I read somewhere that we don't wan't to use `killall` anymore ?

**Comment by NicolaLS** [comment]
I guess the `# FIXME: make db path configurable to avoid cd-ing here` will help with (1.) I'll try to do that tomorrow. (But even if it fixes it..if anybody has an idea why 1. happens pls tell me it bugs me alot because it dosn't make sense to me why it makes a diffrence cd ing into e.g `/run/user/1000/tmp.Aa0zSUkRO2/cfg` or cd ing into `./mycustomdir/cfg`..

**Comment by Maan2003** [comment]
this is because we kill processes FIFO order, but we should kill the processes in LIFO order.

So if server is _started_ after bitcoind, it will be killed _before_ bitcoind

**Comment by NicolaLS** [comment]
this ugly sed expression should fix it: `kill $(cat $PID_FILE | sed '1!G;h;$!d') `

**Comment by Maan2003** [comment]
if that sed expression is just to reverse file
`kill $(tac $PID_FILE)`

**Comment by NicolaLS** [comment]
> if that sed expression is just to reverse file `kill $(tac $PID_FILE)`

it is. I thought since we already use `sed` using it again for this minimizes problems we could have I'm not so experienced with linux is `tac` a basic programm like `sed`

**Comment by justinmoon** [comment]
The one problem with `tac` is that it doesn't exist on MacOS. Ideally all our scripts would work on Mac, too.

**Comment by elsirion** [comment]
> I'd say the code should not be panicking on connection errors or external service responding with an error.

Yeah, had some ideas about that in #37, but the solution wasn't obvious so I postponed it. Pinging @jkitman and @justinmoon for feedback.

Also, the other panics (tokio threads) are just because we lack proper shutdown logic and happens because main died, this can't be triggered by our peers afaik.

**Comment by jkitman** [comment]
Seems like #248 removes most of the error message spam, but a proper shutdown / recovering from certain failures seems like it could be a separate issue, perhaps by modifying #37.
