### ISSUE TITLE
Move `FeeConsensus` into modules

### ISSUE THREAD

**Issue by justinmoon** [fedimint/minimint#313]
This currently exists inside the core consensus code, and includes module-specific fee information from the wallet, mint and lightning modules. These values are more appropriate in the modules themselves.

@elsirion mentioned a good place to store this might be the `InputMeta` type returned by `validate_input` and `apply_input`.

**Comment by rndhouse** [comment]
I'm happy to give this a go! @justinmoon added the following on discord:

> Basicallly, minimint is meant to be very modular. All of the actual functionality (e.g. on-chain deposits and withdrawals, chaumian mint, or lightning integration) should be implemented in modules. e.g. https://github.com/fedimint/minimint/tree/master/modules. This is a nice doc explaining how the transaction model works https://github.com/fedimint/minimint/blob/master/docs/lifecycle.md. Modules define their own input or output types. So you can have a on-chain deposit where the input is a proof that user deposited on-chain bitcoin into the mint, and the outputs are chaumian mint token issuances. So different modules can be combined in transactions.

> This issue is about how module-specific information has leaked into the core system. So we should move this stuff back into the modules.

**Comment by justinmoon** [comment]
It's all yours, @rndhouse!

**Comment by justinmoon** [comment]
This is a good comment about what the final goal is here https://github.com/fedimint/minimint/pull/325#pullrequestreview-1066988064

**Comment by rndhouse** [comment]
@justinmoon Now that PR https://github.com/fedimint/minimint/pull/325 is merged. I think we should close this issue in favor of https://github.com/fedimint/minimint/issues/359 .

**Comment by justinmoon** [comment]
SGTM!
