### ISSUE TITLE
Figure out how to make the Nix CI build faster

### ISSUE THREAD

**Issue by elsirion** [fedimint/minimint#67]
#60 made integration tests in CI slow, maybe caching can help as it did before. Probably needs some special Nix caching.

**Comment by elsirion** [comment]
Actually one really easy thing to do would be building the nix expression for MiniMint first and then using the result inside the integration test to not compile everything twice.

One thing to consider: how to keep it compatible with non-nix users. So probably some flag that switches between the two scenarios and defines some variables with paths to the respecitve binaries.

**Comment by wiredhikari** [comment]
- Have made some changes to avoid building twice and improve build times in #73 . 
- If the user has nix installed on a non-nix system then nix-expressions are expected to work the same as they work on a nixos machine. (Also tested the builds on Gentoo linux)
