### ISSUE TITLE
`default.nix` doesn't build locally on stable NixOS

### ISSUE THREAD

**Issue by elsirion** [fedimint/minimint#78]
We are testing with nix unstable in CI, is there any way to make it run on stable? Or do we just need to wait? This made debugging #77 rather annoying on my machine.

```
minimint$ nix-build 
error: unsupported argument 'submodules' to 'fetchGit', at /nix/store/9zfki3r0ma0vmqin3iwlbv2vmskp4jb7-naersk-src/lib.nix:117:11
(use '--show-trace' to show detailed location information)
```

**Comment by wiredhikari** [comment]
This should have been fixed after [this](https://github.com/fedimint/minimint/pull/73/commits/4522c07013e2b44dae111ae258b2eb4a1249be93)
