### ISSUE TITLE
Fix `default.nix` build

### ISSUE THREAD

**Issue by elsirion** [fedimint/minimint#90]
#73 just removed the test to make CI work again

**Comment by dpc** [comment]
Hi. Just a casual lurker. AFAIK the state of the art for Nix + Rust is:

nix flakes + https://github.com/nix-community/lorri  (soo much better than nix-shell), https://github.com/ipetkov/crane (naersk is good too) + fenix. Here is a PR where I added such a config to another Bitcoin Rust project: https://github.com/mycitadel/mycitadel-desktop/pull/41/files

I hope it's some useful info, feel free to ignore if not. :) There's a lot of helpful people in https://matrix.to/#/#rust:nixos.org , which I wasn't aware before a week ago, so I'll past that too.

**Comment by wiredhikari** [comment]
Thanks for suggestions, I am planning to flakify current configs.
